I would rather be playing No Man's Sky.

diff --git a/.local/bin/audioscript b/.local/bin/audioscript
--- a/.local/bin/audioscript
+++ b/.local/bin/audioscript
@@ -10,7 +10,7 @@ declare backupdir format scriptname="${0##*/}"
 # Functions
 usage()
 {
-	cat <<EOF
+    cat << EOF
 ${scriptname}
 
 Usage: ${scriptname} [OPTS] FILE...
@@ -24,7 +24,7 @@ General options:
   -d, --dryrun                    Perform dry run, do not make any changes
   -h, --help                      Print this message
   -v[LEVEL], --verbose [LEVEL]    Set verbose level. Defaults to 1 if no level
-                                    is given.
+                                    is specified.
                                     1 - FFMPEG log messages
                                     2 - Script messages
                                     3 - Both
@@ -48,94 +48,99 @@ EOF
 
 opt_short='b::de:hv::'
 opt_long=('backup::' 'dryrun' 'extension:' 'help'
-	'verbose::' 'album:' 'artist:' 'comment:' 'genre:' 'title:' 'track:'
-	'year:' 'clear')
+    'verbose::' 'album:' 'artist:' 'comment:' 'genre:' 'title:' 'track:'
+    'year:' 'clear')
 
-TEMP=$(getopt -n 'audioscript' -o "${opt_short}" -l "${opt_long[*]}" -- "$@" || exit 1)
+TEMP=$(getopt -n 'audioscript' -o "${opt_short}" -l "${opt_long[*]}" -- "$@" \
+    || exit 1)
 
 eval set -- "$TEMP"
 unset TEMP
 
 while true; do
-	case "$1" in
-	-b|--backup)
-		backupdir="${2:-backup}"
-		backup=1
-		shift
-		;;
-	-d|--dryrun) dryrun=1 ;;
-	-e|--extension)
-		format="$2"
-		shift
-		;;
-	-h|--help)
-		usage
-		exit 0
-		;;
-	-v|--verbose)
-		verbose="${2:-1}"
-		shift
-		;;
-	--album|--artist|--comment|--genre|--title|--track|--year)
-		metadata+=('-metadata' "${1##*-}=$2")
-		shift
-		;;
-	--clear) clear=1 ;;
-	--)
-		shift
-		break
-		;;
-	*)
-		if [[ $# == 0 ]]; then
-			printf '%b' "${scriptname}: no files specified\n" >&2
-			exit 3
-		fi
+    case "$1" in
+    -b | --backup)
+        backupdir="${2:-backup}"
+        backup=1
+        shift
+        ;;
+    -d | --dryrun) dryrun=1 ;;
+    -e | --extension)
+        format="$2"
+        shift
+        ;;
+    -h | --help)
+        usage
+        exit 0
+        ;;
+    -v | --verbose)
+        verbose="${2:-1}"
+        shift
+        ;;
+    --album | --artist | --comment | --genre | --title | --track | --year)
+        metadata+=('-metadata' "${1##*-}=$2")
+        shift
+        ;;
+    --clear) clear=1 ;;
+    --)
+        shift
+        break
+        ;;
+    *)
+        if [[ $# == 0 ]]; then
+            printf '%b\n' "${scriptname}: no files specified" >&2
+            exit 3
+        fi
 
-		break
-		;;
-	esac
+        break
+        ;;
+    esac
 
-	shift
+    shift
 done
 
 # Sanity check
-if [[ ${dryrun} == 1 && $(( dryrun + backup )) -gt 1 ]]; then
-	printf '%b' "${scriptname}: dryrun, backup: Only one operation allowed at a time\n" >&2
-	exit 4
+if [[ ${dryrun} == 1 && $((dryrun + backup)) -gt 1 ]]; then
+    printf '%b\n' "${scriptname}: dryrun, backup: Only one operation allowed at a time" >&2
+    exit 4
 fi
 
 [[ ${clear} == 1 ]] && opts+=('-map_metadata' '-1')
 
 [[ ${backup} == 1 ]] && mkdir -p "${backupdir}"
 
-case $(( verbose )) in
-	0) opts+=('-loglevel' 'quiet') ;;
-	2) opts+=('-loglevel' 'quiet'); set -xv ;;
-	3) set -xv ;;
+case $((verbose)) in
+0) opts+=('-loglevel' 'quiet') ;;
+2)
+    opts+=('-loglevel' 'quiet')
+    set -xv
+    ;;
+3) set -xv ;;
 esac
 
 for file in "$@"; do
-	if [[ ! -f ${file} ]]; then
-		printf '%b' "${scriptname}: Invalid path ${file}. Skipping...\n" >&2
-		continue
-	fi
+    if [[ ! -f ${file} ]]; then
+        printf '%b\n' "${scriptname}: Invalid path ${file}. Skipping..." >&2
+        continue
+    fi
 
-	extension="${file##*.}"
-	format=${format:-$extension}
-	filename="${file%.*}"
-	newfile="$filename.$format"
+    extension="${file##*.}"
+    format=${format:-$extension}
+    filename="${file%.*}"
+    newfile="$filename.$format"
 
-	if [[ ${dryrun} == 0 ]]; then
-		[[ ${backup} == 1 ]] && cp "${file}" "${backupdir}"
+    if [[ ${dryrun} == 0 ]]; then
+        [[ ${backup} == 1 ]] && cp "${file}" "${backupdir}"
 
-		if [[ ${extension} == "${format}" ]]; then
-			ffmpeg -i "${file}" "${opts[@]}" "${metadata[@]}" -c copy "${newfile}"
-		else
-			ffmpeg -i "${file}" "${opts[@]}" "${metadata[@]}" "${newfile}"
-		fi
+        if [[ ${extension} == "${format}" ]]; then
+            tmp="tmp.${RANDOM}.${extension}"
+            ffmpeg -i "${file}" "${opts[@]}" "${metadata[@]}" -c copy "${tmp}" \
+                && mv "${tmp}" "${file}"
+        else
+            ffmpeg -i "${file}" "${opts[@]}" "${metadata[@]}" "${newfile}" \
+                && rm "${file}"
+        fi
+    fi
 
-		rm "${file}"
-	fi
-
-	printf '%b' "${scriptname}: ${file} => ${newfile}\n"
+    printf '%b\n' "${scriptname}: ${file} => ${newfile}"
 done
diff --git a/.local/bin/latex-build b/.local/bin/latex-build
--- a/.local/bin/latex-build
+++ b/.local/bin/latex-build
@@ -1,46 +1,48 @@
 #!/bin/sh
 
 # Check if biblatex is defined and not commented out
-has_biblatex(){
-	queryall=$(grep -e "^\\\\usepackage.*{biblatex}" -e "^\\\\addbibresource.*{.\+}" "${1}")
+has_biblatex()
+{
+    queryall=$(grep -e "^\\\\usepackage.*{biblatex}" -e "^\\\\addbibresource.*{.\+}" "${1}")
 
-	[ -z "${queryall}" ] && return 1
+    [ -z "${queryall}" ] && return 1
 
-	# If commented out entries are equal to total count
-	[ "$(printf '%s' "${queryall}" | grep -c %)" -eq \
-		"$(printf '%s' "${queryall}" | wc -l)" ] \
-		&& return 1
+    # If commented out entries are equal to total count
+    [ "$(printf '%s' "${queryall}" | grep -c %)" -eq \
+        "$(printf '%s' "${queryall}" | wc -l)" ] \
+        && return 1
 
-	# Use biber to generate references
-	biber "${1}"
+    # Use biber to generate references
+    biber "${1}"
 
-	return 0
+    return 0
 }
 
 # Check whether labels and refs are defined and not commented out
-has_ref_or_label(){
-	queryall=$(grep -e "\\\\ref" -e "\\\\label" "${1}")
+has_ref_or_label()
+{
+    queryall=$(grep -e "\\\\ref" -e "\\\\label" "${1}")
 
-	[ -z "${queryall}" ] && return 1
+    [ -z "${queryall}" ] && return 1
 
-	# If commented out entries are equal to total count
-	[ "$(printf "%s" "${queryall}" | grep -c %)" -eq \
-		"$(printf "%s" "${queryall}" | wc -l)" ] \
-		&& return 1
+    # If commented out entries are equal to total count
+    [ "$(printf "%s" "${queryall}" | grep -c %)" -eq \
+        "$(printf "%s" "${queryall}" | wc -l)" ] \
+        && return 1
 
-	return 0
+    return 0
 }
 
 document=${1}
 
 if [ -z "${document}" ]; then
-	printf "%b" "Error: \"${document}\" is not a valid argument\n"
-	exit 1
+    printf "%b\n" "Error: \"${document}\" is not a valid argument"
+    exit 1
 fi
 
 if [ ! -e "${document}" ]; then
-	printf "%b" "Error: \"${document}\" does not exist\n"
-	exit 2
+    printf "%b\n" "Error: \"${document}\" does not exist"
+    exit 2
 fi
 
 # Compile to pdf for the first time
@@ -48,5 +50,5 @@ pdflatex "${document}"
 
 # Check if recompilation is necessary
 if has_biblatex "${document}" || has_ref_or_label "${document}"; then
-	pdflatex "${document}"
+    pdflatex "${document}"
 fi
diff --git a/.local/bin/recursively b/.local/bin/recursively
--- a/.local/bin/recursively
+++ b/.local/bin/recursively
@@ -8,7 +8,7 @@ pattern=""
 
 usage()
 {
-	cat <<EOF
+    cat << EOF
 ${scriptname}
 
 Usage: ${scriptname} [OPTION] COMMAND...
@@ -46,7 +46,7 @@ traverse()
 
         if [ -n "${lpattern}" ]; then
             case "${file}" in
-                *"${lpattern}"*) ${command} "${file}" ;;
+            *"${lpattern}"*) ${command} "${file}" ;;
             esac
         else
             ${command} "${file}"
@@ -56,33 +56,33 @@ traverse()
 
 while true; do
     case "$1" in
-        -d|--directory)
-            dir="${2}" 
+    -d | --directory)
+        dir="${2}"
 
-            if [ ! -e "${dir}" ]; then
-                printf '%b\n' "${scriptname}: ${dir} does not exist" >&2
-                exit 1
-            fi
+        if [ ! -e "${dir}" ]; then
+            printf '%b\n' "${scriptname}: ${dir} does not exist" >&2
+            exit 1
+        fi
 
-            shift 2
-            ;;
-        -h|--help) usage && exit 0 ;;
-        -p|--pattern) pattern="${2}" && shift 2 ;;
-        --) shift ;;
-        *)
-            if [ ${#} -eq 0 ]; then
-                printf '%b\n' "${scriptname}: no files specified" >&2
-                exit 2
-            fi
+        shift 2
+        ;;
+    -h | --help) usage && exit 0 ;;
+    -p | --pattern) pattern="${2}" && shift 2 ;;
+    --) shift ;;
+    *)
+        if [ ${#} -eq 0 ]; then
+            printf '%b\n' "${scriptname}: no files specified" >&2
+            exit 2
+        fi
 
-            if ! which "${1}" > /dev/null 2>&1; then
-                printf '%b\n' "${scriptname}: command not found" >&2
-                exit 3
-            fi
+        if ! which "${1}" > /dev/null 2>&1; then
+            printf '%b\n' "${scriptname}: command not found" >&2
+            exit 3
+        fi
 
-            command="${*}"
-            break
-            ;;
+        command="${*}"
+        break
+        ;;
     esac
 done
 
